version : '3'
name: k8s-test
services:

  k8ss-server1:
    container_name: k8s-test-service1
    build:
      context: .
      dockerfile: service1-dockerfile
    ports:
      - "8081:8081"
    privileged: true
    volumes:
      - ./service1:/home/service1/log
      - ./service1:/home/service1/uploadPath

  k8ss-server2:
    container_name: k8s-test-service2
    build:
      context: .
      dockerfile: service2-dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./service1:/home/service2/log
      - ./service1:/home/service2/uploadPath